# Generated by Django 4.2.7 on 2024-01-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.URLField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
