# Generated by Django 4.2.7 on 2024-01-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
