# Generated by Django 4.2.7 on 2023-11-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_useraccountdemo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
