# Generated by Django 4.2.7 on 2024-01-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
