# Generated by Django 4.2.7 on 2023-11-06 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraccount_bio_alter_useraccount_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, size=None),
        ),
    ]
