# Generated by Django 4.2.7 on 2023-11-06 11:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_useraccount_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='followers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
