# Generated by Django 4.2.7 on 2023-11-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useraccount_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
