# Generated by Django 4.2.7 on 2023-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('m', 'Message'), ('p', 'Post'), ('l', 'Like'), ('c', 'Comment')], default=None)),
                ('sender', models.IntegerField(blank=True, default=None, null=True)),
                ('receiver', models.IntegerField(blank=True, default=None, null=True)),
                ('content', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
