# Generated by Django 4.2.7 on 2024-02-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_sender_notification_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
